defmodule Snow.Cosmos.Examples do
  def example_1 do
    """
    ...#......
    .......#..
    #.........
    ..........
    ......#...
    .#........
    .........#
    ..........
    .......#..
    #...#.....
    """
  end

  def my_input do
    File.read!("priv/input/Day 11 input.txt")
  end
end
